
jobs:
  build-cbs-mock:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build cbs-mock Docker image
          command: |
            cd cbs-mock
            docker build -t cbs-mock:latest .
      - run:
          name: Log in to Docker Registry
          command: docker login $PUBLISH_CONTAINER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Tag and push Docker images with tags
          command: |
            docker tag cbs-mock:latest ${DOCKER_ORG:-mojaloop}/${CIRCLE_PROJECT_REPONAME}-cbs-mock:$CIRCLE_TAG
            docker push ${DOCKER_ORG:-mojaloop}/${CIRCLE_PROJECT_REPONAME}-cbs-mock:$CIRCLE_TAG
            docker tag cbs-mock:latest ${DOCKER_ORG:-mojaloop}/${CIRCLE_PROJECT_REPONAME}-cbs-mock:$RELEASE_TAG
            docker push ${DOCKER_ORG:-mojaloop}/${CIRCLE_PROJECT_REPONAME}-cbs-mock:$RELEASE_TAG

workflows:
  build_and_test:
    jobs:
      - build-cbs-mock:
          name: CBS Mock Docker release
          context: org-global
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /v\d+(\.\d+){2}(-[a-zA-Z-][0-9a-zA-Z-]*\.\d+)?/
          requires:
            - Lint
            - Vulnerability check
            - License audit
            - License scan
            - Grype image scan