@startuml name="payer-initiates-merchant-payment"

skinparam defaultFontSize 10
autonumber

participant "Standard Bank Customer App" as App
participant "Core Connector" as CC
participant "ML Connector" as ML

note over App
{
    "homeTransactionId": "HTX123456789",
    "payeeId": "12123143524",
    "payeeIdType": "MSISDN",
    "sendCurrency": "MWK",
    "receiveAmount": "150.00",
    "receiveCurrency": "ZMW",
    "transactionDescription": "Payment for services",
    "transactionType": "TRANSFER",
    "payer": {
        "name": "John Doe",
        "payerId": "99984747232",
        "DateAndPlaceOfBirth": {
            "BirthDt": "20-09-1990",
            "PrvcOfBirth": "ProvinceOfBirth",
            "CityOfBirth": "Blantyre",
            CtryOfBirth: "Malawi"
        }
    }
}
end note
App ->> CC: POST /merchant-payment/

CC ->> CC: Check Request

alt If Checks fail
    CC -->> App: Response 400
end

CC ->> ML: POST /transfer /{amountType: RECEIVE}

note over ML, CC
{
  "completedTimestamp": "1600-02-29T17:23:30.274Z",
  "fulfilment": "WLctttbu2HvTsa1",
  "homeTransactionId": "string",
  "transferState": "RECEIVED"
}
end note
ML -->> CC: Response

CC ->> CC: Check Response

alt If Checks fail
    CC -->> App: Response 500
end

alt If WAITING_FOR_QUOTE_ACCEPTANCE
    CC ->> CC: Check returned Quote
    alt If Quote is invalid
        CC ->> ML: PUT /transfers/{id}[acceptQuote: false]
        CC -->> App: Response 500
    end
    CC ->> ML: PUT /transfers/{id}[acceptQuote: true]
end

ML -->> CC: Response, fxQuote

alt If response not successful
    CC -->> App: Response 500
end

CC ->> CC: Check Conversion Terms

alt If Conversion invalid
    CC -->> App: Response 500
end


note over CC
{
    "payeeDetails": {
        "idType": "MSISDN",
        "idValue": "12123143524",
        "fspId": "airtelzambia",
        "name": "John Doe",
    },
    "sendAmount": "150.00",
    "sendCurrency": "MWK",
    "receiveAmount": "140.00",
    "receiveCurrency": "ZMW",
    "targetFees": "10.00",
    "sourceFees": "10.00",
    "transactionId": "GHGIFEIE11828",
    "homeTransactionId": "1213ads-fsfa11-efgg131-3sdfs4", 
}
end note
CC -->> App: Response 200

App ->> App: Show terms of transfer to customer

@enduml
