@startuml name="payer-initiates-merchant-payment"

skinparam defaultFontSize 10
autonumber

participant "Standard Bank Customer App" as App
participant "Core Connector" as CC
participant "ML Connector" as ML

note over App, CC
{
  "homeTransactionId": "HTX123456789",
  "payeeId": "16135551212",
  "payeeIdType": "MSISDN",
  "sendAmount": "150.00",
  "sendCurrency": "UGX",
  "receiveCurrency": "KES",
  "transactionDescription": "Payment for services",
  "transactionType": "TRANSFER",
  "payer": {
    "name": "John Doe",
    "payerId": "9876543210",
    "DateAndPlaceOfBirth": {
      "BirthDt": "20-09-2001",
      "PrvcOfBirth": "ProvinceOfBirth",
      "CityOfBirth": "Kampala",
      "CtryOfBirth": "Uganda"
    }
  }
}
end note
App ->> CC: POST /merchant-payment/

CC ->> CC: Check Request

alt If Checks fail
    CC -->> App: Response 400
end

CC ->> ML: POST /transfer /{amountType: RECEIVE}

note over ML, CC
{
  "completedTimestamp": "1600-02-29T17:23:30.274Z",
  "fulfilment": "WLctttbu2HvTsa1",
  "homeTransactionId": "string",
  "transferState": "RECEIVED"
}
end note
ML -->> CC: Response

CC ->> CC: Check Response

alt If Checks fail
    CC -->> App: Response 500
end

alt If WAITING_FOR_QUOTE_ACCEPTANCE
    CC ->> CC: Check returned Quote
    alt If Quote is invalid
        CC ->> ML: PUT /transfers/{id}[acceptQuote: false]
        CC -->> App: Response 500
    end
    CC ->> ML: PUT /transfers/{id}[acceptQuote: true]
end

ML -->> CC: Response, fxQuote

alt If response not successful
    CC -->> App: Response 500
end

CC ->> CC: Check Conversion Terms

alt If Conversion invalid
    CC -->> App: Response 500
end

CC -->> App: Response 200

App ->> App: Show terms of transfer to customer

@enduml
