openapi: 3.0.3
info:
  title: Example Core Banking System API
  version: 1.0.0
  description: A generic example API for core banking system operations
tags:
  - name: Authentication
    description: Authentication and authorization operations
  - name: Accounts
    description: Account management operations
  - name: Transactions
    description: Transaction processing operations
paths:
  /auth/token:
    post:
      summary: Generate an access token
      description: Issues a new access token for authentication.
      operationId: generateAccessToken
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  description: Client identifier
                client_secret:
                  type: string
                  description: Client secret
              required:
                - client_id
                - client_secret
      responses:
        '200':
          description: Access token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: The generated access token
                  token_type:
                    type: string
                    description: Type of token (e.g., Bearer)
                  expires_in:
                    type: integer
                    description: Token expiration time in seconds
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /accounts/{accountId}/info:
    get:
      summary: Retrieve account information
      description: Fetches basic account information for the given account ID.
      operationId: getAccountInfo
      tags:
        - Accounts
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: The unique identifier of the account
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Account information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_id:
                    type: string
                    description: Unique account identifier
                  account_name:
                    type: string
                    description: Name associated with the account
                  account_type:
                    type: string
                    description: Type of account (e.g., savings, checking)
                  balance:
                    type: number
                    format: decimal
                    description: Current account balance
                  currency:
                    type: string
                    description: Account currency code
                  status:
                    type: string
                    description: Account status (active, inactive, blocked)
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal server error
  /transactions:
    post:
      summary: Create a transaction
      description: Initiates a new transaction between accounts.
      operationId: createTransaction
      tags:
        - Transactions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from_account:
                  type: string
                  description: Source account identifier
                to_account:
                  type: string
                  description: Destination account identifier
                amount:
                  type: number
                  format: decimal
                  description: Transaction amount
                currency:
                  type: string
                  description: Currency code
                description:
                  type: string
                  description: Transaction description
              required:
                - from_account
                - to_account
                - amount
                - currency
      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: string
                    description: Unique transaction identifier
                  status:
                    type: string
                    description: Transaction status
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '422':
          description: Insufficient funds or invalid account
        '500':
          description: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT