#!/bin/sh

for dir in */; do
    case "$dir" in
        *-core-connector/)
            cd "$dir" || exit 1
            npm run dep:check
            npm run test:unit
            cd - > /dev/null || exit 1
            ;;
    esac
done