#!/bin/sh

for dir in */; do
    case "$dir" in
        *-core-connector/)
            cd "$dir" || exit 1
            npx lint-staged
            npm run lint:fix
            cd - > /dev/null || exit 1
            ;;
    esac
done
